// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users(created_at,updated_at,email)
VALUES(NOW(),NOW(),$1)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreateUsers(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}
